### ISSUE TITLE
Do your engine support updates?

### ISSUE THREAD

**Issue by Monaco-a-Knox** [DCNick3/shin#32]
Entergram released three patches in 2021, fixing several problems in Umineko. Is it possible apply thoses fix using your engine?

Umineko 1.0.3 (01006A300BA2C800)/(20.7MB) ? They also released patches for other games, such as Gerokasu.

**Comment by DCNick3** [comment]
It.. Probably does?

Honestly, I don't really know what have they fixed in the updates, as I have not diffed them. If have some info about what've been fixed - please let me know, I will make sure to make it work =)

However, if it's smth like small bugfixes, I believe it wouldn't actually matter that much, as I have taken a lot of liberties with this reimplementation. The code is very different, so I do not expect any bug-to-bug compatibility (making the bugfixes mostly irrelevant?)

**Comment by Monaco-a-Knox** [comment]
https://www.entergram.co.jp/umineko/special_updatepatch.html

1.0.1
- wrong/missing background
1.0.2
- fix voice/bgm bug.
- option to unlock new episode
- typos
- -others fix
1.0.3
- more typos

**Comment by DCNick3** [comment]
Thanks for pointer to where find those notes (didn't expect notes from the developer to actually be useful, lol)

*after fighting switch tooling for some time*

Aha, so this actually includes a romfs update in form of a `patch.rom` (like the higurashi!). For reference, `sha265sum` of the 1.0.3 umineko update is `4c82e74e13fe13e974545211b332c93f73d10a7f63ddcd461db73f47e341fcd8`.

This is actually easy to support and all the code to this is in the engine already, just a matter of loading an additional rom file/directory. I'll make sure it is supported

**Comment by DCNick3** [comment]
Pushed an update (along with a bug fix to sdu). Hopefully the build will succeed and it will be available as to download in about 25 minutes

**Comment by Monaco-a-Knox** [comment]
Apparently it works, but I haven't tested the whole game.

Could you add the name of the game in the window? Like this:
![image](https://user-images.githubusercontent.com/58667780/222306348-5022cfed-4ce3-454e-a000-3ba916dce407.png)

**Comment by DCNick3** [comment]
> the whole game.

The whole game won't work, there's a bunch of stuff from the engine not implemented yet ;)
